# Generated by Django 5.1.15 on 2026-08-18 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Excellence'), ('SPORTS', 'Sports & Athletics'), ('CULTURAL', 'Cultural & Arts'), ('SOCIAL', 'Community Service'), ('LEADERSHIP', 'Leadership'), ('OTHER', 'Other Contribution')], default='ACADEMIC', max_length=30)),
                ('level', models.CharField(choices=[('SCHOOL', 'School Level'), ('DISTRICT', 'District Level'), ('STATE', 'State Level'), ('NATIONAL', 'National Level'), ('INTERNATIONAL', 'International Level')], default='SCHOOL', max_length=30)),
                ('points', models.IntegerField(default=5)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
