# Generated by Django 5.1.15 on 2026-08-18 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('award_type', models.CharField(choices=[('STUDENT_OF_THE_MONTH', 'Student of the Month'), ('MOST_IMPROVED', 'Most Improved Student'), ('ACADEMIC_EXCELLENCE', 'Academic Excellence Award'), ('BEST_ATTENDANCE', 'Best Attendance Award'), ('BEST_BEHAVIOUR', 'Best Behaviour Award'), ('OUTSTANDING_PARTICIPATION', 'Outstanding Participation Award'), ('ACHIEVEMENT_AWARD', 'Special Achievement Award')], default='STUDENT_OF_THE_MONTH', max_length=40)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested (Pending Approval)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='academics.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='students.student')),
            ],
            options={
                'ordering': ['-year', '-month', '-awarded_at'],
                'unique_together': {('student', 'academic_year', 'month', 'year', 'award_type')},
            },
        ),
    ]
