# Generated by Django 5.1.15 on 2026-08-18 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_academic', models.DecimalField(decimal_places=2, default=40.0, help_text='Academic weight % (e.g. 40)', max_digits=5)),
                ('weight_attendance', models.DecimalField(decimal_places=2, default=15.0, help_text='Attendance weight % (e.g. 15)', max_digits=5)),
                ('weight_behaviour', models.DecimalField(decimal_places=2, default=15.0, help_text='Behaviour weight % (e.g. 15)', max_digits=5)),
                ('weight_participation', models.DecimalField(decimal_places=2, default=10.0, help_text='Participation weight % (e.g. 10)', max_digits=5)),
                ('weight_assignments', models.DecimalField(decimal_places=2, default=5.0, help_text='Assignments weight % (e.g. 5)', max_digits=5)),
                ('weight_improvement', models.DecimalField(decimal_places=2, default=10.0, help_text='Improvement weight % (e.g. 10)', max_digits=5)),
                ('weight_achievements', models.DecimalField(decimal_places=2, default=5.0, help_text='Achievements weight % (e.g. 5)', max_digits=5)),
                ('min_attendance_threshold', models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum attendance % required', max_digits=5)),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_setting', to='academics.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('academic_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('behaviour_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('participation_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('assignment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('improvement_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('achievement_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('holistic_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=20)),
                ('risk_recommendation', models.TextField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='academics.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scores', to='students.student')),
            ],
            options={
                'ordering': ['-year', '-month', '-holistic_score'],
                'unique_together': {('student', 'academic_year', 'month', 'year')},
            },
        ),
    ]
