# Generated by Django 5.2.17 on 2026-08-19 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTeacherMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Term 1 Academic & Attendance Review', max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_type', models.CharField(choices=[('ONLINE', 'Online Video Conference'), ('IN_PERSON', 'In-Person (School Campus)')], default='ONLINE', max_length=20)),
                ('location_or_link', models.CharField(default='https://meet.google.com/student360-ptm', help_text='Google Meet link or Room Number (e.g. Room 204)', max_length=255)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested (Pending Confirmation)'), ('SCHEDULED', 'Scheduled / Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('agenda_notes', models.TextField(blank=True, help_text='Initial agenda or topics to discuss', null=True)),
                ('summary_feedback', models.TextField(blank=True, help_text='Post-meeting summary and actionable feedback recorded by teacher', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptm_meetings', to='students.parent')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ptms', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptm_meetings', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptm_meetings', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
