# Generated by Django 5.2.17 on 2026-08-19 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Excellence'), ('ATTENDANCE', 'Attendance Streak'), ('BEHAVIOUR', 'Behaviour & Conduct'), ('ASSIGNMENT', 'Homework & Assignments'), ('OVERALL', 'Holistic Champion')], default='ACADEMIC', max_length=20)),
                ('icon', models.CharField(default='fa-award', help_text='FontAwesome icon class (e.g. fa-fire, fa-crown, fa-bolt)', max_length=50)),
                ('xp_reward', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('current_attendance_streak', models.IntegerField(default=0)),
                ('current_homework_streak', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to='students.student')),
            ],
            options={
                'ordering': ['-total_xp'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_students', to='gamification.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to='students.student')),
            ],
            options={
                'ordering': ['-earned_date'],
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
